name: Execute Python Script

on:
  workflow_dispatch:


jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.9'

      - name: Install Dependencies and Run Script
        run: |
          python -m pip install --upgrade pip
          pip install pymongo
          pip install yfinance
          python save_banco.py
      - name: List Installed Packages
        run: |
          pip list

