name: Execute Python Script

on:
  schedule:
    - cron: '0 2 * * *'  # Executa todos os dias às 02:00 UTC

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Execute Python Script
        run: python save_banco.py  
