name: Execute Python Script

on:
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.9'

      - name: Install Dependencies and Run Script
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
          pip install scikit-learn
          pip install matplotlib
          pip install seaborn
          pip install pymongo
          pip install dnspython
          pip install yfinance
          python model_training.py
          python predict.py
      - name: List Installed Packages
        run: |
          pip list

      - name: Configuring git credentials
        run: |
          git config --global user.email "leonardo@rodaelli.com.br"
          git config --global user.name "LeoRodaelli"

      - name: Set up repository
        run: |
          git remote set-url origin https://LeoRodaelli:${{ secrets.GH_TOKEN }}@github.com/LeoRodaelli/investAI.git

      - name: Make changes
        run: |
          echo "Log of automatic commit at $(date)" >> autocommit.log

      - name: Commit and push if changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add .
          git commit -m "Automated commit on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin HEAD:main
